/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Fenêtre
 * Android class: WIN_Main
 * Date: 12/07/2021 14:54:03
 * Version of wdjava.dll: 23.0.98.0
 */


package com.mycompany.dreamglass.wdgen;


import com.mycompany.dreamglass.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.ui.champs.fenetre.*;
import fr.pcsoft.wdjava.ui.champs.saisie.*;
import fr.pcsoft.wdjava.ui.cadre.*;
import fr.pcsoft.wdjava.ui.champs.bouton.*;
import fr.pcsoft.wdjava.media.*;
import fr.pcsoft.wdjava.core.poo.*;
import fr.pcsoft.wdjava.api.*;
import fr.pcsoft.wdjava.net.http.*;
import fr.pcsoft.wdjava.ui.champs.combo.*;
import fr.pcsoft.wdjava.core.types.collection.tableau.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.ui.activite.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class GWDFWIN_Main extends WDFenetre
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs de WIN_Main
////////////////////////////////////////////////////////////////////////////

/**
 * EDT_Codigo
 */
class GWDEDT_Codigo extends WDChampSaisieSimple
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°1 de WIN_Main.EDT_Codigo
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectLibelle(0,0,300,21);
super.setRectCompPrincipal(0,21,300,40);
super.setQuid(2370677031133383693l);

super.setChecksum("784885200");

super.setNom("EDT_Codigo");

super.setType(20001);

super.setLibelle("Nota");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(0);

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 8);

super.setTailleInitiale(300, 63);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(1);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(1);

super.setModeAscenseur(2, 2);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(2);

super.setMiseABlancSiZero(true);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, creerPolice_GEN("Roboto", -8.000000, 0), 3, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Edt@dpi160.png?E5_3NP_8_8_8_8", new int[] {1,4,1,2,2,2,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 1, 5));

super.setStyleSaisie(0x222222, creerPolice_GEN("Roboto", -8.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDEDT_Codigo mWD_EDT_Codigo;

/**
 * BTN_Scanner
 */
class GWDBTN_Scanner extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°2 de WIN_Main.BTN_Scanner
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(2370677112741254335l);

super.setChecksum("788378149");

super.setNom("BTN_Scanner");

super.setType(4);

super.setLibelle("Scanner");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 135);

super.setTailleInitiale(304, 48);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(2);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setNumTab(5);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Scanner
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_qr_code = WDVarNonAllouee.ref;


// qr_code is BarCode = BCCapture()
vWD_qr_code = new WDInstance( new WDCodeBarres() );

vWD_qr_code.setValeur(WDAPICodeBarres.cbCapture());


// EDT_Codigo = qr_code..RoughValue
mWD_EDT_Codigo.setValeur(vWD_qr_code.getProp(EWDPropriete.PROP_VALEURBRUTE));

// ExecuteProcess(BTN_Consultar,trtClick)
WDAPIVM.executeTraitement(mWD_BTN_Consultar,18);

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Scanner mWD_BTN_Scanner;

/**
 * BTN_Consultar
 */
class GWDBTN_Consultar extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°3 de WIN_Main.BTN_Consultar
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(2370677181460943601l);

super.setChecksum("788590695");

super.setNom("BTN_Consultar");

super.setType(4);

super.setLibelle("Consultar");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 79);

super.setTailleInitiale(304, 48);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(3);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setNumTab(3);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Consultar
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_http = WDVarNonAllouee.ref;
WDObjet vWD_Httpurl_Teste = new WDChaineU();



// http is httpRequest
vWD_http = new WDInstance( new WDHTTPRequete() );


// http.Method = httpGet
vWD_http.setProp(EWDPropriete.PROP_METHODE,1);

// http.URL = "http://192.168.1.176/consultas/ConsultarNota.php?valor="+EDT_Codigo
vWD_http.setProp(EWDPropriete.PROP_URL,new WDChaineU("http://192.168.1.176/consultas/ConsultarNota.php?valor=").opPlus(mWD_EDT_Codigo));

// Httpurl_Teste is string = "http://www.bing.com"  

vWD_Httpurl_Teste.setValeur("http://www.bing.com");


// IF HTTPRequest(Httpurl_Teste) = True AND Httpurl_Teste <> "" THEN    
if((WDAPIHttp.HTTPRequete(vWD_Httpurl_Teste.getString()).opEgal(true) & vWD_Httpurl_Teste.opDiff("")))
{
// 	resp is restResponse = RESTSend(http)
WDObjet vWD_resp = WDVarNonAllouee.ref;
vWD_resp = new WDInstance( new WDHTTPReponse() );

vWD_resp.setValeur(WDAPIHttp.HTTPEnvoie(vWD_http));


// 	if resp..StatusCode = 200 or resp..StatusCode = "OK" THEN
if((vWD_resp.getProp(EWDPropriete.PROP_CODEETAT).opEgal(200) | vWD_resp.getProp(EWDPropriete.PROP_CODEETAT).opEgal("OK")))
{
// 	    sVerJSON is ANSI string = resp.Content
WDObjet vWD_sVerJSON = new WDChaineA();


vWD_sVerJSON.setValeur(vWD_resp.getProp(EWDPropriete.PROP_CONTENU));


// 	    EDT_Resultado_Consulta..Visible = True
mWD_EDT_Resultado_Consulta.setProp(EWDPropriete.PROP_VISIBLE,true);

// 	    EDT_Resultado_Consulta = sVerJSON
mWD_EDT_Resultado_Consulta.setValeur(vWD_sVerJSON);

// 		IF sVerJSON >= 5 THEN
if(vWD_sVerJSON.opSupEgal(5))
{
// 			COMBO_Operario..Visible = True
mWD_COMBO_Operario.setProp(EWDPropriete.PROP_VISIBLE,true);

// 			BTN_Siguiente_Etapa..Visible = true
mWD_BTN_Siguiente_Etapa.setProp(EWDPropriete.PROP_VISIBLE,true);

}
else
{
// 			ExecuteProcess(BTN_Siguiente_Etapa,trtClick)
WDAPIVM.executeTraitement(mWD_BTN_Siguiente_Etapa,18);

// 			COMBO_Operario..Visible = False
mWD_COMBO_Operario.setProp(EWDPropriete.PROP_VISIBLE,false);

// 			BTN_Siguiente_Etapa..Visible = false
mWD_BTN_Siguiente_Etapa.setProp(EWDPropriete.PROP_VISIBLE,false);

}

}
else
{
// 		Error("Problemas de envio")	
WDAPIDialogue.erreur("Problemas de envio");

}

}
else
{
// 	Error("No tienes conexion a internet vuelva a intentar")	
WDAPIDialogue.erreur("No tienes conexion a internet vuelva a intentar");

}

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Consultar mWD_BTN_Consultar;

/**
 * EDT_Resultado_Consulta
 */
class GWDEDT_Resultado_Consulta extends WDChampSaisieMultiLigne
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°4 de WIN_Main.EDT_Resultado_Consulta
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectLibelle(0,0,300,21);
super.setRectCompPrincipal(0,21,300,100);
super.setQuid(2370901717837695776l);

super.setChecksum("570134511");

super.setNom("EDT_Resultado_Consulta");

super.setType(20001);

super.setLibelle("Informacion");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(0);

super.setNavigable(true);

super.setEtatInitial(1);

super.setPositionInitiale(8, 299);

super.setTailleInitiale(300, 123);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(4);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(8);

super.setModeAscenseur(2, 1);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(2);

super.setMiseABlancSiZero(true);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, creerPolice_GEN("Roboto", -8.000000, 0), 3, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Edt@dpi160.png?E5_3NP_8_8_8_8", new int[] {1,4,1,2,2,2,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 1, 5));

super.setStyleSaisie(0x222222, creerPolice_GEN("Roboto", -8.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDEDT_Resultado_Consulta mWD_EDT_Resultado_Consulta;

/**
 * EDT_Etapa
 */
class GWDEDT_Etapa extends WDChampSaisieSimple
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°5 de WIN_Main.EDT_Etapa
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectLibelle(0,2,58,40);
super.setRectCompPrincipal(58,2,246,40);
super.setQuid(2370904178857805544l);

super.setChecksum("573976386");

super.setNom("EDT_Etapa");

super.setType(20001);

super.setLibelle("Etapa");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setTaille(0);

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(-379, 95);

super.setTailleInitiale(304, 44);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setMotDePasse(false);

super.setTypeSaisie(0);

super.setMasqueSaisie(new WDChaineU("0"));

super.setTailleMin(0, 0);

super.setTailleMax(134217727, 134217727);

super.setVisibleInitial(true);

super.setAltitude(5);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setEllipse(0);

super.setIndication("");

super.setNumTab(4);

super.setModeAscenseur(2, 2);

super.setEffacementAutomatique(true);

super.setFinSaisieAutomatique(false);

super.setLettreAppel(65535);

super.setSelectionEnAffichage(true);

super.setPersistant(false);

super.setClavierEnSaisie(true);

super.setMasqueAffichage(new WDChaineU(""));

super.setParamBtnActionClavier(0, "");

super.setRetraitGauche(2);

super.setMiseABlancSiZero(false);

super.setVerifieOrthographe(true);

super.setTauxParallaxe(0, 0);

super.setBoutonSuppression(0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, creerPolice_GEN("Roboto", -8.000000, 0), -2, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Edt@dpi160.png?E5_3NP_8_8_8_8", new int[] {1,4,1,2,2,2,1,4,1}, new int[] {8, 8, 8, 8}, 0xFFFFFFFF, 1, 5));

super.setStyleSaisie(0x222222, creerPolice_GEN("Roboto", -11.000000, 0));

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDEDT_Etapa mWD_EDT_Etapa;

/**
 * BTN_Siguiente_Etapa
 */
class GWDBTN_Siguiente_Etapa extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°6 de WIN_Main.BTN_Siguiente_Etapa
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(2370904217515994538l);

super.setChecksum("577460637");

super.setNom("BTN_Siguiente_Etapa");

super.setType(4);

super.setLibelle("Siguiente Etapa");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 243);

super.setTailleInitiale(300, 48);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(6);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setNumTab(7);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Siguiente_Etapa
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_http = WDVarNonAllouee.ref;
WDObjet vWD_Httpurl_Teste = new WDChaineU();



// http is httpRequest
vWD_http = new WDInstance( new WDHTTPRequete() );


// http.Method = httpPost
vWD_http.setProp(EWDPropriete.PROP_METHODE,2);

// http.URL = "http://192.168.1.176/consultas/NotasEHistorial.php?valor="+EDT_Codigo+"&"+"OP"+COMBO_Operario[COMBO_Operario]..StoredValue
vWD_http.setProp(EWDPropriete.PROP_URL,new WDChaineU("http://192.168.1.176/consultas/NotasEHistorial.php?valor=").opPlus(mWD_EDT_Codigo).opPlus("&").opPlus("OP").opPlus(mWD_COMBO_Operario.get(mWD_COMBO_Operario).getProp(EWDPropriete.PROP_VALEURMEMORISEE)));

// Httpurl_Teste is string = "http://www.bing.com"  

vWD_Httpurl_Teste.setValeur("http://www.bing.com");


// IF HTTPRequest(Httpurl_Teste) = True AND Httpurl_Teste <> "" THEN
if((WDAPIHttp.HTTPRequete(vWD_Httpurl_Teste.getString()).opEgal(true) & vWD_Httpurl_Teste.opDiff("")))
{
// 	IF YesNo("Quieres continuar con la actualizacion?") = Yes THEN
if(WDAPIDialogue.ouiNon("Quieres continuar con la actualizacion?").opEgal(1))
{
// 		resp is restResponse = RESTSend(http)
WDObjet vWD_resp = WDVarNonAllouee.ref;
vWD_resp = new WDInstance( new WDHTTPReponse() );

vWD_resp.setValeur(WDAPIHttp.HTTPEnvoie(vWD_http));


// 		IF resp..StatusCode = 200 THEN
if(vWD_resp.getProp(EWDPropriete.PROP_CODEETAT).opEgal(200))
{
// 			ToastDisplay("Correcto!",toastShort,vaTop,haCenter)
WDAPIToast.toastAffiche("Correcto!",0,0,1);

// 			EDT_Resultado_Consulta..Visible = False
mWD_EDT_Resultado_Consulta.setProp(EWDPropriete.PROP_VISIBLE,false);

// 			EDT_Resultado_Consulta = ""
mWD_EDT_Resultado_Consulta.setValeur("");

}
else
{
// 			Error("Problemas de envio")	
WDAPIDialogue.erreur("Problemas de envio");

}

}
else
{
// 		COMBO_Operario..Visible = False
mWD_COMBO_Operario.setProp(EWDPropriete.PROP_VISIBLE,false);

// 		BTN_Siguiente_Etapa..Visible = False
this.setProp(EWDPropriete.PROP_VISIBLE,false);

// 		EDT_Resultado_Consulta..Visible = False
mWD_EDT_Resultado_Consulta.setProp(EWDPropriete.PROP_VISIBLE,false);

// 		EDT_Codigo = ""
mWD_EDT_Codigo.setValeur("");

// 		EDT_Resultado_Consulta = ""
mWD_EDT_Resultado_Consulta.setValeur("");

// 		SetFocus(EDT_Codigo)
WDAPIDivers.donneFocus(mWD_EDT_Codigo);

}

}
else
{
// 	Error("Error retrieving data.")
WDAPIDialogue.erreur("Error retrieving data."
);

}

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Siguiente_Etapa mWD_BTN_Siguiente_Etapa;

/**
 * COMBO_Operario
 */
class GWDCOMBO_Operario extends WDCombo
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°7 de WIN_Main.COMBO_Operario
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setRectLibelle(0,2,83,40);
super.setRectCompPrincipal(83,2,221,40);
super.setNom("COMBO_Operario");

super.setType(10002);

super.setLibelle("Operario");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(8, 191);

super.setTailleInitiale(304, 44);

super.setValeurInitiale("");

super.setPlan(0);

super.setCadrageHorizontal(0);

super.setContenuInitial("");

super.setTriee(false);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(false);

super.setAltitude(7);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setNumTab(6);

super.setLettreAppel(65535);

super.setRetourneValeurProgrammation(false);

super.setPersistant(false);

super.setTauxParallaxe(0, 0);

super.setPresenceLibelle(true);

super.setStyleLibelle(0x222222, creerPolice_GEN("Roboto", -8.000000, 0), -2, 0, 0x808080);

super.setCadreExterieur(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0, 0, 0, 0);

super.setCadreInterne(WDCadreFactory.creerCadre_GEN("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Combo@dpi160.png?E5_3NP_32_6_42_6", new int[] {1,4,1,2,2,2,1,4,1}, new int[] {6, 42, 6, 32}, 0xFFFFFFFF, 1, 5));

super.setStyleElement(0x222222, 0xFFFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 48);

super.setStyleSelection(0x222222, 0xE2E2E2, creerPolice_GEN("Roboto", -8.000000, 0));

super.setStyleBouton(WDCadreFactory.creerCadre_GEN(1, 0xE1E1E1, 0x616161, 0xFFFFFFFF, 4, 4, 1, 1), 0xFFFFFFFF);

activerEcoute();
super.terminerInitialisation();
}

// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDCOMBO_Operario mWD_COMBO_Operario;

/**
 * BTN_Combo
 */
class GWDBTN_Combo extends WDBouton
{

////////////////////////////////////////////////////////////////////////////
// Déclaration des champs du fils n°8 de WIN_Main.BTN_Combo
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.initialiserObjet();
super.setFenetre( getWDFenetreThis() );
super.setQuid(2371301493400180077l);

super.setChecksum("576793266");

super.setNom("BTN_Combo");

super.setType(4);

super.setLibelle("Combo");

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setNavigable(true);

super.setEtatInitial(0);

super.setPositionInitiale(-256, 33);

super.setTailleInitiale(160, 48);

super.setPlan(0);

super.setImageEtat(1);

super.setImageFondEtat(5);

super.setTailleMin(0, 0);

super.setTailleMax(2147483647, 2147483647);

super.setVisibleInitial(true);

super.setAltitude(8);

super.setAncrageInitial(0, 1000, 1000, 1000, 1000, 0);

super.setNumTab(2);

super.setLettreAppel(65535);

super.setTypeBouton(0);

super.setTypeActionPredefinie(0);

super.setBoutonOnOff(false);

super.setTauxParallaxe(0, 0);

super.setLibelleVAlign(1);

super.setLibelleHAlign(1);

super.setPresenceLibelle(true);

super.setImage("", 0, 2, 1, null, null, null);

super.setStyleLibelleRepos(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleSurvol(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setStyleLibelleEnfonce(0xFFFFFF, creerPolice_GEN("Roboto", -8.000000, 0), 0, 0x808080);

super.setCadreRepos(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreSurvol(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setCadreEnfonce(WDCadreFactory.creerCadre_GEN(2, 0xF39621, 0x731600, 0xF39621, 4, 4, 1, 1));

super.setImageFond9Images(new int[] {1,2,1,2,2,2,1,2,1}, 10, 10, 10, 10);

super.setImageFond("C:\\My Mobile Projects\\DreamGlass\\Templates\\WM\\210 Material Design Blue\\Material Design Blue_Btn_Std@dpi160.png?E5_3NP_10_10_10_10", 1, 0, 1, 1);

activerEcoute();
super.terminerInitialisation();
}

/**
 * Traitement: Click BTN_Combo
 */
public void clicSurBoutonGauche()
{
super.clicSurBoutonGauche();


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables locales au traitement
// (En WLangage les variables sont encore visibles après la fin du bloc dans lequel elles sont déclarées)
////////////////////////////////////////////////////////////////////////////
WDObjet vWD_http = WDVarNonAllouee.ref;
WDObjet vWD_Httpurl_Teste = new WDChaineU();



// http is httpRequest
vWD_http = new WDInstance( new WDHTTPRequete() );


// http.Method = httpPost
vWD_http.setProp(EWDPropriete.PROP_METHODE,2);

// http.URL = "http://192.168.1.176/consultas/Combo.php"
vWD_http.setProp(EWDPropriete.PROP_URL,"http://192.168.1.176/consultas/Combo.php");

// Httpurl_Teste is string = "http://www.bing.com"  

vWD_Httpurl_Teste.setValeur("http://www.bing.com");


// IF HTTPRequest(Httpurl_Teste) = True AND Httpurl_Teste <> "" THEN 
if((WDAPIHttp.HTTPRequete(vWD_Httpurl_Teste.getString()).opEgal(true) & vWD_Httpurl_Teste.opDiff("")))
{
// 	resp is restResponse = RESTSend(http)
WDObjet vWD_resp = WDVarNonAllouee.ref;
vWD_resp = new WDInstance( new WDHTTPReponse() );

vWD_resp.setValeur(WDAPIHttp.HTTPEnvoie(vWD_http));


// 	IF resp..StatusCode = 200 THEN
if(vWD_resp.getProp(EWDPropriete.PROP_CODEETAT).opEgal(200))
{
// 		sVerJSON is ANSI string = resp.Content
WDObjet vWD_sVerJSON = new WDChaineA();


vWD_sVerJSON.setValeur(vWD_resp.getProp(EWDPropriete.PROP_CONTENU));


// 		sVerFormat is string = sVerJSON
WDObjet vWD_sVerFormat = new WDChaineU();


vWD_sVerFormat.setValeur(vWD_sVerJSON);


// 		arrARRAY_Respuesta is array of strings
WDObjet vWD_arrARRAY_Respuesta = WDVarNonAllouee.ref;
vWD_arrARRAY_Respuesta = new WDTableauSimple(1, new int[]{0}, 0, 16);

// 		arrARRAY_Respuesta = StringSplit(sVerFormat,",",ccNormal)
vWD_arrARRAY_Respuesta.setValeur(WDAPIChaine.chaineDecoupe(vWD_sVerFormat,new WDChaineU(","),0));

// 		ListDeleteAll(COMBO_Operario)
WDAPIListe.listeSupprimeTout(mWD_COMBO_Operario);

// 		nTOTAL is int=ArrayCount(arrARRAY_Respuesta)
WDObjet vWD_nTOTAL = new WDEntier4();


vWD_nTOTAL.setValeur(WDAPITableau.tableauOccurrence(vWD_arrARRAY_Respuesta));


// 		i is int
WDObjet vWD_i = new WDEntier4();



// 		ListAdd(COMBO_Operario,"Selecciona una opcion"+gLink("Selecciona una opcion"))
WDAPIListe.listeAjoute(mWD_COMBO_Operario,new WDChaineU("Selecciona una opcion").opPlus(WDAPIDessin.gLien("Selecciona una opcion")).getString());

// 		FOR i = 1 TO nTOTAL -1
for(vWD_i.setValeur(1);vWD_i.opInfEgal(vWD_nTOTAL.opMoins(1));vWD_i.opInc())
{
// 		ListAdd(COMBO_Operario,arrARRAY_Respuesta[i+1]+ gLink(arrARRAY_Respuesta[i]))
WDAPIListe.listeAjoute(mWD_COMBO_Operario,vWD_arrARRAY_Respuesta.get(vWD_i.opPlus(1)).opPlus(WDAPIDessin.gLien(vWD_arrARRAY_Respuesta.get(vWD_i).getString())).getString());

// 		i++
vWD_i.opInc();

}

}

}
else
{
// 	ExecuteProcess(BTN_Combo,trtClick)	
WDAPIVM.executeTraitement(this,18);

}

}




// Activation des écouteurs: 
public void activerEcoute()
{
super.activerEcouteurClic();
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
}
public GWDBTN_Combo mWD_BTN_Combo;

/**
 * Traitement: Global declarations of WIN_Main
 */
public void declarerGlobale(WDObjet[] WD_tabParam)
{
super.declarerGlobale(WD_tabParam);
int WD_ntabParamLen = 0;
if(WD_tabParam!=null) WD_ntabParamLen = WD_tabParam.length;

// Traitement du paramètre n°0
if(0<WD_ntabParamLen) 
{
vWD_gsNombre = WD_tabParam[0];
}
else { vWD_gsNombre = null; erreurPassageParametreFenetre(WD_ntabParamLen, 1); }
super.ajouterVariableGlobale("gsNombre",vWD_gsNombre);


vWD_gsNombre = WDParametre.traiterParametre(vWD_gsNombre, 1, false, 16);


}




/**
 * Traitement: End of initialization of WIN_Main
 */
public void init()
{
super.init();

// ExecuteProcess(BTN_Combo,trtClick)
WDAPIVM.executeTraitement(mWD_BTN_Combo,18);

// ToastDisplay("Bienvenido " + gsNombre,toastShort,vaTop,haCenter)
WDAPIToast.toastAffiche(new WDChaineU("Bienvenido ").opPlus(vWD_gsNombre).getString(),0,0,1);

// SetFocus(EDT_Codigo)
WDAPIDivers.donneFocus(mWD_EDT_Codigo);

}




// Activation des écouteurs: 
public void activerEcoute()
{
}

////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
 public WDObjet vWD_gsNombre = WDVarNonAllouee.ref;
////////////////////////////////////////////////////////////////////////////
// Création des champs de la fenêtre WIN_Main
////////////////////////////////////////////////////////////////////////////
protected void creerChamps()
{
mWD_EDT_Codigo = new GWDEDT_Codigo();
mWD_BTN_Scanner = new GWDBTN_Scanner();
mWD_BTN_Consultar = new GWDBTN_Consultar();
mWD_EDT_Resultado_Consulta = new GWDEDT_Resultado_Consulta();
mWD_EDT_Etapa = new GWDEDT_Etapa();
mWD_BTN_Siguiente_Etapa = new GWDBTN_Siguiente_Etapa();
mWD_COMBO_Operario = new GWDCOMBO_Operario();
mWD_BTN_Combo = new GWDBTN_Combo();

}
////////////////////////////////////////////////////////////////////////////
// Initialisation de la fenêtre WIN_Main
////////////////////////////////////////////////////////////////////////////
public  void initialiserObjet()
{
super.setQuid(2370676872214838353l);

super.setChecksum("784998872");

super.setNom("WIN_Main");

super.setType(1);

super.setMenuContextuelSysteme();

super.setNote("", "");

super.setCouleur(0x0);

super.setCouleurFond(0xFFFFFF);

super.setPositionInitiale(0, 0);

super.setTailleInitiale(320, 455);

super.setTitre("Main");

super.setTailleMin(-1, -1);

super.setTailleMax(20000, 20000);

super.setVisibleInitial(true);

super.setPositionFenetre(3);

super.setPersistant(true);

super.setGFI(true);

super.setAnimationFenetre(0);

super.setImageFond("", 1, 0, 1);

super.setCouleurTexteAutomatique(0xF4000000);

super.setCouleurBarreSysteme(0xFF000001);


activerEcoute();

////////////////////////////////////////////////////////////////////////////
// Initialisation des champs de WIN_Main
////////////////////////////////////////////////////////////////////////////
mWD_EDT_Codigo.initialiserObjet();
super.ajouter("EDT_Codigo", mWD_EDT_Codigo);
mWD_BTN_Scanner.initialiserObjet();
super.ajouter("BTN_Scanner", mWD_BTN_Scanner);
mWD_BTN_Consultar.initialiserObjet();
super.ajouter("BTN_Consultar", mWD_BTN_Consultar);
mWD_EDT_Resultado_Consulta.initialiserObjet();
super.ajouter("EDT_Resultado_Consulta", mWD_EDT_Resultado_Consulta);
mWD_EDT_Etapa.initialiserObjet();
super.ajouter("EDT_Etapa", mWD_EDT_Etapa);
mWD_BTN_Siguiente_Etapa.initialiserObjet();
super.ajouter("BTN_Siguiente_Etapa", mWD_BTN_Siguiente_Etapa);
mWD_COMBO_Operario.initialiserObjet();
super.ajouter("COMBO_Operario", mWD_COMBO_Operario);
mWD_BTN_Combo.initialiserObjet();
super.ajouter("BTN_Combo", mWD_BTN_Combo);

super.terminerInitialisation();
}

////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}
/**
* Retourne le mode d'affichage de l'ActionBar de la fenêtre.
*/
public int getModeActionBar()
{
return 0;
}
/**
* Retourne vrai si la fenêtre est maximisée, faux sinon.
*/
public boolean isMaximisee()
{
return true;
}
/**
* Retourne vrai si la fenêtre a une barre de titre, faux sinon.
*/
public boolean isAvecBarreDeTitre()
{
return false;
}
/**
* Retourne le mode d'affichage de la barre système de la fenêtre.
*/
public int getModeBarreSysteme()
{
return 1;
}
/**
* Retourne vrai si la fenêtre est munie d'ascenseurs automatique, faux sinon.
*/
public boolean isAvecAscenseurAuto()
{
return true;
}
/**
* Retourne Vrai si on doit appliquer un theme "dark" (sombre) ou Faux si on doit appliquer "light" (clair) à la fenêtre.
* Ce choix se base sur la couleur du libellé par défaut dans le gabarit de la fenêtre.
*/
public boolean isThemeDark()
{
return false;
}
/**
* Retourne vrai si l'option de masquage automatique de l'ActionBar lorsqu'on scrolle dans un champ de la fenêtre a été activée.
*/
public boolean isMasquageAutomatiqueActionBar()
{
return false;
}
public static class WDActiviteFenetre extends WDActivite
{
protected WDFenetre getFenetre()
{
return GWDPDreamGlass.ms_Project.mWD_WIN_Main;
}
}
/**
* Retourne le nom du gabarit associée à la fenêtre.
*/
public String getNomGabarit()
{
return "210 MATERIAL DESIGN BLUE#WM";
}
}
