/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Projet
 * Android class: DreamGlass
 * Date: 12/07/2021 15:03:51
 * Version of wdjava.dll: 23.0.98.0
 */


package com.mycompany.dreamglass.wdgen;


import com.mycompany.dreamglass.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/





public class GWDPDreamGlass extends WDProjet
{
/**
 * Accès au projet: DreamGlass
 * Pour accéder au projet à partir de n'importe où: 
 * GWDPDreamGlass.ms_Project
 */
public static GWDPDreamGlass ms_Project;

 // WIN_Main
public GWDFWIN_Main mWD_WIN_Main = new GWDFWIN_Main();
 // accesseur de WIN_Main
public GWDFWIN_Main getWIN_Main()
{
mWD_WIN_Main.verifierOuverte();
return mWD_WIN_Main;
}

 // WIN_Loging
public GWDFWIN_Loging mWD_WIN_Loging = new GWDFWIN_Loging();
 // accesseur de WIN_Loging
public GWDFWIN_Loging getWIN_Loging()
{
mWD_WIN_Loging.verifierOuverte();
return mWD_WIN_Loging;
}

 // WIN_Acerca_de
public GWDFWIN_Acerca_de mWD_WIN_Acerca_de = new GWDFWIN_Acerca_de();
 // accesseur de WIN_Acerca_de
public GWDFWIN_Acerca_de getWIN_Acerca_de()
{
mWD_WIN_Acerca_de.verifierOuverte();
return mWD_WIN_Acerca_de;
}


 // Constructeur de la classe GWDPDreamGlass
public GWDPDreamGlass()
{
ajouterFenetre("WIN_Main", mWD_WIN_Main);
ajouterFenetre("WIN_Loging", mWD_WIN_Loging);
ajouterFenetre("WIN_Acerca_de", mWD_WIN_Acerca_de);

}


////////////////////////////////////////////////////////////////////////////
// Déclaration des variables globales
////////////////////////////////////////////////////////////////////////////
static
{
// Allocation de l'objet global
GWDPDreamGlass.ms_Project = new GWDPDreamGlass();

// Définition des langues du projet
GWDPDreamGlass.ms_Project.setLangueProjet(new int[] {2}, new int[] {0}, 2, false);
GWDPDreamGlass.ms_Project.setNomCollectionProcedure(new String[]{});
// Palette des couleurs
GWDPDreamGlass.ms_Project.setPaletteCouleurGabarit(new int[] {0x394AE1, 0x26A0FA, 0x6DBC61, 0x85A800, 0xD2AC54, 0xC9822B, 0xA95CF8, 0xB86592, 0xB74A5E, 0x654E44, 0xA5A595});
}
public String getVersionApplication(){ return "0.0.8.0";}
public String getNomSociete(){ return "";}
public String getNomAPK(){ return "DreamGlass";}
public int getIdNomApplication(){return com.mycompany.dreamglass.R.string.app_name;}
public boolean isModeAnsi(){ return false;}
public boolean isAffectationTableauParCopie(){ return true;}
public boolean isAssistanceAutoHFActive(){ return true;}
public String getPackageRacine(){ return "com.mycompany.dreamglass";}
public int getIdIconeApplication(){ return com.mycompany.dreamglass.R.drawable.i_c_o_n_e________0;}
public int getInfoPlateforme(EWDInfoPlateforme info)
{
switch(info)
{
case DPI_ECRAN : return 160;
case HAUTEUR_BARRE_SYSTEME : return 25;
case HAUTEUR_BARRE_TITRE : return 25;
case HAUTEUR_ACTION_BAR : return 48;
case HAUTEUR_BARRE_BAS : return 0;
case HAUTEUR_ECRAN : return 480;
case LARGEUR_ECRAN : return 320;
default : return 0;
}
}
public boolean isActiveThemeMaterialDesign()
{
return true;
}
////////////////////////////////////////////////////////////////////////////
public String getAdresseEmail() 
{
return "";
}
public boolean isIgnoreErreurCertificatHTTPS()
{
return false;
}
////////////////////////////////////////////////////////////////////////////
public boolean isUniteAffichageLogique()
{
return false;
}

////////////////////////////////////////////////////////////////////////////
// Formats des masques du projet
////////////////////////////////////////////////////////////////////////////
public String getFichierWDM()
{
return null;
}
protected void declarerRessources()
{
super.ajouterFichierAssocie("C:\\MY MOBILE PROJECTS\\DREAMGLASS\\TEMPLATES\\WM\\210 MATERIAL DESIGN BLUE\\MATERIAL DESIGN BLUE_COMBO.PNG?E5_3NP_32_6_42_6",com.mycompany.dreamglass.R.drawable.material_design_blue_combo_5_np3_32_6_42_6_selector, "");
super.ajouterFichierAssocie("C:\\MY MOBILE PROJECTS\\DREAMGLASS\\TEMPLATES\\WM\\210 MATERIAL DESIGN BLUE\\MATERIAL DESIGN BLUE_PICT_SAVE_16_5.PNG",com.mycompany.dreamglass.R.drawable.material_design_blue_pict_save_16_5_4, "");
super.ajouterFichierAssocie("C:\\MY MOBILE PROJECTS\\DREAMGLASS\\TEMPLATES\\WM\\210 MATERIAL DESIGN BLUE\\MATERIAL DESIGN BLUE_EDT.PNG?E5_3NP_8_8_8_8",com.mycompany.dreamglass.R.drawable.material_design_blue_edt_3_np3_8_8_8_8_selector, "");
super.ajouterFichierAssocie("C:\\MY MOBILE PROJECTS\\DREAMGLASS\\TEMPLATES\\WM\\210 MATERIAL DESIGN BLUE\\MATERIAL DESIGN BLUE_BTN_STD.PNG?E5_3NP_10_10_10_10",com.mycompany.dreamglass.R.drawable.material_design_blue_btn_std_2_np3_10_10_10_10_selector, "");
}


/**
 * Appel des méthodes d'initialisation des classes / collections de procédures / projet
 */
static void GWDPDreamGlass_InitProjet( String [] args)
{
GWDPDreamGlass.ms_Project.initialiserProjet("DreamGlass", "Android application", args);
}

/**
 * Appel des méthodes de terminaison des projet / collections de procédures / classes
 */
static protected void GWDPDreamGlass_TermineProjet()
{

// Terminaison des collections de procédures et des classes

// Libération de l'objet global
GWDPDreamGlass.ms_Project = null;
}

/**
 * Lancer de l'application Android
 */
public static class WDLanceur extends WDAbstractLanceur
{
public void init()
{
// Appel des méthodes d'initialisation
GWDPDreamGlass_InitProjet(null);
}
public void run()
{

GWDPDreamGlass.ms_Project.lancerProjet();
}
}
}
