/**
 * Code generated by WINDEV Mobile - DO NOT MODIFY!
 * WINDEV Mobile object: Splash Screen
 * Android class: DreamGlass
 * Date: 12/07/2021 15:03:51
 * Version of wdjava.dll: 23.0.98.0
 */


package com.mycompany.dreamglass.wdgen;


import com.mycompany.dreamglass.*;
import fr.pcsoft.wdjava.core.types.*;
import fr.pcsoft.wdjava.core.*;
import fr.pcsoft.wdjava.core.application.*;
import fr.pcsoft.wdjava.ui.style.degrade.*;
/*Imports trouvés dans le code WL*/
/*Fin Imports trouvés dans le code WL*/



public class WDSplashScreenGen implements IWDSplashScreen
{
public int getIdImageFond(){return com.mycompany.dreamglass.R.drawable.s_p_l_a_s_c_r_e_e_n________1;}
public int getModeAffichageImageFond(){return 8;}
public int getIdNomApplication(){return com.mycompany.dreamglass.R.string.splashscreen_title;}
public int getIdInfoVersion(){return com.mycompany.dreamglass.R.string.splashscreen_version;}
public int getIdLogo(){return 0;}
public boolean isAvecAnimationChargement(){return true;}
public int getIdMessageChargement(){return com.mycompany.dreamglass.R.string.splashscreen_message;}
public int getCouleurLibelle(){return 0xFFFFFF;}
public IWDDegrade getFondDegrade(){return null;}
public int getCouleurFond(){return 0xFFFFFF;}
}
